# Generated by Django 5.0.1 on 2024-02-03 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_reportfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfile',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='report.report'),
        ),
    ]
