# Generated by Django 5.0.2 on 2024-02-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
