# Generated by Django 5.0.1 on 2024-03-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('', '과를 선택해주세요'), ('빅데이터 클라우드공학과', '빅데이터 클라우드공학과'), ('컴퓨터공학부', '컴퓨터공학부')], default='컴퓨터공학부', max_length=20),
        ),
    ]
