# Generated by Django 5.0.1 on 2024-03-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(choices=[('', '학년을 선택해주세요'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10),
        ),
    ]
