# Generated by Django 5.0.1 on 2024-03-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_grade'),
        ('user', '0004_alter_userprofile_bio'),
    ]

    operations = [
    ]
