# Generated by Django 5.0.1 on 2024-03-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='profile_img',
        ),
    ]
