# Generated by Django 5.0.1 on 2024-03-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_profile_picture_userprofile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.CharField(choices=[('', '학년을 선택해주세요'), ('1', '1학년'), ('2', '2학년'), ('3', '3학년'), ('4', '4학년')], max_length=10),
        ),
    ]
