# Generated by Django 5.0.1 on 2024-03-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_userprofile_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(default='profile_img/default-profile.png', upload_to='profile_img/'),
        ),
    ]
