# Generated by Django 5.0.1 on 2024-02-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_alter_mentorship_mentee_alter_mentorship_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorship',
            name='status',
            field=models.CharField(choices=[('', '상태를 선택하세요'), ('Active', 'Active'), ('Completed', 'Completed'), ('Pending', 'Pending')], max_length=20),
        ),
    ]
