# Generated by Django 5.0.1 on 2024-02-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0002_alter_mentorship_status'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorship',
            name='mentee',
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentee',
            field=models.ManyToManyField(related_name='mentorships_as_mentee', to='user.userprofile'),
        ),
    ]
