# Generated by Django 5.0.1 on 2024-03-17 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0003_remove_mentorship_mentee_mentorship_mentee'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('mentorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorship.mentorship')),
            ],
        ),
        migrations.AddConstraint(
            model_name='weeklyscore',
            constraint=models.UniqueConstraint(fields=('mentorship', 'week'), name='unique_mentorship_week'),
        ),
    ]
