# Generated by Django 5.0.1 on 2024-04-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0004_weeklyscore_weeklyscore_unique_mentorship_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyscore',
            name='score',
            field=models.IntegerField(),
        ),
    ]
